---
domain: test
descriptors:
  - key: destination_cluster
    rate_limit:
      unit: minute
      requests_per_unit: 50
      
  - key: client_id
    value: foo
    rate_limit:
      unit: minute
      requests_per_unit: 3

  - key: destination_cluster
    value: hello
    rate_limit:
      unit: minute
      requests_per_unit: 3

  - key: generic_key
    value: bar
    rate_limit:
      unit: minute
      requests_per_unit: 3
